# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the beta version"
  lane :beta do

  cocoapods(
    clean: true,
    podfile: "Podfile"
  )

  build_app(scheme: "AffordIQ",
            workspace: "AffordIQ.xcworkspace",
            include_bitcode: true,
            export_method: "ad-hoc")
  end

  desc "Run unit tests"
  lane :tests do

    cocoapods(
      clean: true,
      podfile: "Podfile"
    )

    run_tests(workspace: "AffordIQ.xcworkspace",
              devices: ["iPhone 8"],
              scheme: "AffordIQ")
  end
end
